// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/gitDiff.ts";
import * as $1 from "./routes/blame.tsx";
import * as $2 from "./routes/blob.tsx";
import * as $3 from "./routes/commit.tsx";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/log.tsx";
import * as $6 from "./routes/show.tsx";
import * as $7 from "./routes/tree.tsx";
import * as $$0 from "./islands/CommitPreview.tsx";

const manifest = {
  routes: {
    "./routes/api/gitDiff.ts": $0,
    "./routes/blame.tsx": $1,
    "./routes/blob.tsx": $2,
    "./routes/commit.tsx": $3,
    "./routes/index.tsx": $4,
    "./routes/log.tsx": $5,
    "./routes/show.tsx": $6,
    "./routes/tree.tsx": $7,
  },
  islands: {
    "./islands/CommitPreview.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
